services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'daily_diet'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /home/ale/Estudos/ROCKETSEAT/mysql:/var/lib/mysql